# Generated by Django 3.0.3 on 2020-02-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='maild',
            new_name='mail',
        ),
    ]
